version: "3"

services:
  sqlite-container:
    image: alpine:latest
    volumes:
      - ./db:/data
    command: sh -c "apk --no-cache add sqlite && sqlite3 /data/db.sqlite && tail -f /dev/null"
    container_name: sqlite-container
